version: '2'
services:
  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      links:
        - "php"
      volumes:
        - ~/opt:/opt
      environment:
        TZ: Asia/Shanghai
      # restart: always

  php:
      build: ./php
      container_name: php
      ports:
        - "9000:9000"
      links:
        - "mysql"
        # - "memcache"
        - "redis"
  #      - "gearman"
      volumes:
        - ~/opt:/opt
      environment:
        TZ: Asia/Shanghai

  mysql:
      build: ./mysql
      container_name: mysql
      ports:
        - "3306:3306"
      volumes:
        - ~/opt/data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        TZ: Asia/Shanghai

  # memcache:
  #    image: hhxsv5/memcached
  #    ports:
  #      - "11211:11211"

  redis:
      build: ./redis
      container_name: redis
      ports:
        - "6379:6379"
      environment:
        TZ: Asia/Shanghai

  #gearman:
  #    build: ./gearman
  #    ports:
  #      - "4730:4730"
  #    volumes:
  #      - ~/opt:/opt
