version: '2'
services:
  # php:
      # build: ./php
      # container_name: php
      # ports:
      #   - "9000:9000"
      #   - "8011:8011"
      #   - "8001:8001"
      #   - "8002:8002"
      #   - "8003:8003"
      #   - "8004:8004"
      # extra_hosts:
      #   - "test.com:172.18.0.4"
      # links:
      #   - "redis:redis"
      #   # - "ssdb:ssdb"
      #   # - "memcache"
      #   # - "gearman"
      # volumes:
      #   - "~/Documents/docker/www:/docker/www"
      #   - "~/Documents/docker/log:/docker/log"
      # environment:
      #   TZ: "Asia/Shanghai"
      # working_dir: "/docker"
      # restart: "no"

  php7:
      build: ./php7
      container_name: php7
      ports:
        - "9000:9000"
        - "8011:8011"
        - "8001:8001"
        - "8002:8002"
        - "8003:8003"
        - "8004:8004"
      links:
        - "redis:redis"
        # - "ssdb:ssdb"
        # - "memcache"
        # - "gearman"
      volumes:
        - "~/Documents/docker/www:/docker/www"
        - "~/Documents/docker/log:/docker/log"
      environment:
        TZ: "Asia/Shanghai"
      working_dir: "/docker"
      restart: "no"

  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      links:
        # - "php:php"
        - "php7:php7"
      volumes:
        - "~/Documents/docker/www:/docker/www"
        - "~/Documents/docker/log:/docker/log"
      working_dir: "/docker"
      restart: "no"

  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    working_dir: "/root"
    restart: "no"

  # ssdb:
  #   build: ./ssdb
  #   container_name: ssdb
  #   ports:
  #     - "8888:8888"
  #   working_dir: "/root"
  #   restart: "no"
