version: '2'
services:
  php:
      build: ./php
      container_name: php
      links:
        - "redis:redis"
        # - "mysql"
        # - "memcache"
        # - "gearman"
      volumes:
        - "~/Documents/docker/www:/docker/www"
        - "~/Documents/docker/log:/docker/log"
      environment:
        TZ: "Asia/Shanghai"
      working_dir: "/docker"
      restart: always

  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      links:
        - "php:php"
      volumes:
        - "~/Documents/docker/www:/docker/www"
        - "~/Documents/docker/log:/docker/log"
      working_dir: "/docker"
      restart: always

  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always